# Joints limits
#
# Sources:
#
#  - Universal Robots e-Series, User Manual, UR5e, Version 5.8
#    https://s3-eu-west-1.amazonaws.com/ur-support-site/69091/99404_UR5e_User_Manual_en_Global.pdf
#  - Support > Articles > UR articles > Max. joint torques
#    https://www.universal-robots.com/articles/ur-articles/max-joint-torques
#    retrieved: 2020-06-16, last modified: 2020-06-09
#
# NOTE: Acceleration limits are not publicly available so we have picked a reasonable upper limit
joint_limits:
  panda_joint1:
    has_acceleration_limits: true
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_acceleration: !degrees 30.0
    max_effort: 150.0
    max_position: !degrees  180.0
    max_velocity: !degrees  30.0
    min_position: !degrees -180.0
  panda_joint2:
    has_acceleration_limits: true
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_acceleration: !degrees 30.0
    max_effort: 150.0
    max_position: !degrees  90.0
    max_velocity: !degrees  30.0
    min_position: !degrees -270.0
  panda_joint3:
    has_acceleration_limits: true
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_acceleration: !degrees 30.0
    max_effort: 150.0
    max_velocity: !degrees  30.0
    min_position: !degrees -180.0
  panda_joint4:
    has_acceleration_limits: true
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_acceleration: !degrees 30.0
    max_effort: 28.0
    max_position: !degrees  180.0
    max_velocity: !degrees  60.0
    min_position: !degrees -180.0
  panda_joint5:
    has_acceleration_limits: true
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_acceleration: !degrees 30.0
    max_effort: 28.0
    max_position: !degrees  180.0
    max_velocity: !degrees  60.0
    min_position: !degrees -180.0
  panda_joint6:
    has_acceleration_limits: true
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_acceleration: !degrees 30.0
    max_effort: 28.0
    max_position: !degrees  360.0
    max_velocity: !degrees  60.0
    min_position: !degrees -360.0
  panda_joint7:
    has_acceleration_limits: true
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_acceleration: !degrees 30.0
    max_effort: 28.0
    max_position: !degrees  360.0
    max_velocity: !degrees  60.0
    min_position: !degrees -360.0
