# Placeholders for camera configuration.
# Cameras are not a requirement for running MoveIt Pro, but this is provided as an
# example for plugging in Realsense D415 camera topics to the application.

- scene_camera:
    camera_name: "scene_camera"
    type: "sim"
    use: True
    serial_no: "0"
    device_type: "D415"
    framerate: 6
    image_width: 640
    image_height: 480
    enable_pointcloud: False

    # information about the topics the camera publishes the raw image and info
    rgb_info: "/scene_camera/color/camera_info"
    rgb_image: "/scene_camera/color/image_raw"

    registered_rgb_depth_pair:
      depth_info: "/scene_camera/color/camera_info"
      depth_image: "/scene_camera/depth/image_rect_raw"
      registered_info: "/scene_camera/color/camera_info"
      registered_image: "/scene_camera/depth/image_rect_raw"

- fst_wrist_mounted_camera:
    camera_name: "fst_wrist_mounted_camera"
    type: "sim"
    use: True
    serial_no: "0"
    device_type: "D415"
    framerate: 6
    image_width: 640
    image_height: 480
    enable_pointcloud: True

    # information about the topics the camera publishes the raw image and info
    rgb_info: "/fst_wrist_mounted_camera/color/camera_info"
    rgb_image: "/fst_wrist_mounted_camera/color/image_raw"

    # By adding registered_rgb_depth_pair, This camera can be used for "Set Transform From Click"
    registered_rgb_depth_pair:
      depth_info: "/fst_wrist_mounted_camera/depth/camera_info"
      depth_image: "/fst_wrist_mounted_camera/depth/image_rect_raw"
      registered_info: "/fst_wrist_mounted_camera/depth_registered/camera_info"
      registered_image: "/fst_wrist_mounted_camera/depth_registered/image_rect"

- snd_wrist_mounted_camera:
    camera_name: "snd_wrist_mounted_camera"
    type: "sim"
    use: True
    serial_no: "0"
    device_type: "D415"
    framerate: 6
    image_width: 640
    image_height: 480
    enable_pointcloud: True

    # information about the topics the camera publishes the raw image and info
    rgb_info: "/snd_wrist_mounted_camera/color/camera_info"
    rgb_image: "/snd_wrist_mounted_camera/color/image_raw"

    # By adding registered_rgb_depth_pair, This camera can be used for "Set Transform From Click"
    registered_rgb_depth_pair:
      depth_info: "/snd_wrist_mounted_camera/depth/camera_info"
      depth_image: "/snd_wrist_mounted_camera/depth/image_rect_raw"
      registered_info: "/snd_wrist_mounted_camera/depth_registered/camera_info"
      registered_image: "/snd_wrist_mounted_camera/depth_registered/image_rect"

- trd_wrist_mounted_camera:
    camera_name: "trd_wrist_mounted_camera"
    type: "sim"
    use: True
    serial_no: "0"
    device_type: "D415"
    framerate: 6
    image_width: 640
    image_height: 480
    enable_pointcloud: True

    # information about the topics the camera publishes the raw image and info
    rgb_info: "/trd_wrist_mounted_camera/color/camera_info"
    rgb_image: "/trd_wrist_mounted_camera/color/image_raw"

    # By adding registered_rgb_depth_pair, This camera can be used for "Set Transform From Click"
    registered_rgb_depth_pair:
      depth_info: "/trd_wrist_mounted_camera/depth/camera_info"
      depth_image: "/trd_wrist_mounted_camera/depth/image_rect_raw"
      registered_info: "/trd_wrist_mounted_camera/depth_registered/camera_info"
      registered_image: "/trd_wrist_mounted_camera/depth_registered/image_rect"

- fth_wrist_mounted_camera:
    camera_name: "fth_wrist_mounted_camera"
    type: "sim"
    use: True
    serial_no: "0"
    device_type: "D415"
    framerate: 6
    image_width: 640
    image_height: 480
    enable_pointcloud: True

    # information about the topics the camera publishes the raw image and info
    rgb_info: "/fth_wrist_mounted_camera/color/camera_info"
    rgb_image: "/fth_wrist_mounted_camera/color/image_raw"

    # By adding registered_rgb_depth_pair, This camera can be used for "Set Transform From Click"
    registered_rgb_depth_pair:
      depth_info: "/fth_wrist_mounted_camera/depth/camera_info"
      depth_image: "/fth_wrist_mounted_camera/depth/image_rect_raw"
      registered_info: "/fth_wrist_mounted_camera/depth_registered/camera_info"
      registered_image: "/fth_wrist_mounted_camera/depth_registered/image_rect"
