#
#  This contains information for a unique instance of a robot.
#

# Name of the package to specialize
based_on_package: "picknik_ur_sim_config"
hardware:
  robot_description:
    urdf_params:
      - mujoco_model: "description/lab_scene.xml"