SetupMTCPickObject:
  approach_distance: 0.05
  arm_group_name: manipulator
  end_effector_closed_pose_name: close
  end_effector_group_name: gripper
  end_effector_name: moveit_ee
  hand_frame_name: grasp_link
  lift_distance: 0.05
  world_frame_name: world
