# This file defines mappings between ROS 1 and ROS 2 interfaces.
# It is used with the ros1_bridge to allow for communication between ROS 1 and ROS 2.

- 
  ros1_package_name: 'moveit_studio_vision_msgs'
  ros1_action_name: 'GetMasks2D'
  ros2_package_name: 'picknik_ur_site_config'
  ros2_action_name: 'GetMasks2D'
  feedback_fields_1_to_2:
    swquence: 'partial_sequence'