based_on_package: "ur_tutorial_base"

hardware:

  # Be sure to set your robot's IP address.
  ip: "0.0.0.0"
  simulated: True


objectives:
  waypoints_file:
    package_name: "ur_tutorial_base"
    relative_path: "waypoints/ur5e_waypoints.yaml"
  objective_library_paths:
    # You must use a unique key for each package.
    # The ur_tutorial_base uses "core"
    mock_hardware_objectives:
      package_name: "ur_tutorial_empty"
      relative_path: "objectives"
