#
#  This contains information for a unique instance of a robot.
#

# Name of the package to specialize
based_on_package: "picknik_ur5e_base_config"

hardware:
  type: "ur10e"
  ip: 0.0.0.0
  simulated: ${MOCK_HARDWARE:-true}
  # Parameters used to configure the robot description through XACRO
  robot_description:
    urdf:
      package: "picknik_ur_mock_hardware"
      path: "description/picknik_ur.xacro"
    urdf_params:
      - name: "%>> hardware.type"
      - kinematics_parameters_file:
          package: "ur_description"
          path: "config"
      - physical_parameters_file:
          package: "ur_description"
          path: "config"
      - visual_parameters_file:
          package: "ur_description"
          path: "config"

optional_feature_params:
  gazebo_gui: False
  gazebo_verbose: False


