###############################################################
#
#  This configures the robot to work with moveit studio
#
###############################################################

# Baseline hardware configuration parameters for MoveIt Studio.
# [Required]
hardware:
  # Used by the ur_description package to set kinematics and geometry for a specific robot type.
  # You can change this to another UR model but you must update any configuration affected by the different arm size.
  # UR models in the ur_description package are ur3, ur3e, ur5, ur5e, ur10, ur10e, and ur16e.
  # [Required]
  type: ${UR_HARDWARE_TYPE:-ur5e}

  # Set simulated to false if you are using this as a configuration for real hardware.
  # [Required]
  simulated: True

  # If MoveIt Studio should launch the ros2 controller node.
  # [Optional, default=True]
  launch_control_node: True

  # If MoveIt Studio should launch the robot state publisher.
  # [Optional, default=True]
  launch_robot_state_publisher: True

  # The robot's IP address.
  # [Required]
  ip: "0.0.0.0"

  # Specify additional launch files for running the robot with real hardware.
  # [Required]
  robot_driver_persist_launch_file:
    package: "picknik_ur_base_config"
    path: "launch/robot_drivers_to_persist.launch.py"
  hardware_launch_file:
    package: "picknik_ur_base_config"
    path: "launch/hardware.launch.py"

  # Specify any additional launch files for running the robot in simulation mode.
  # Used when simulated is True.
  # [Required]
  simulated_robot_driver_persist_launch_file:
    package: "picknik_ur_base_config"
    path: "launch/sim/robot_drivers_to_persist_sim.launch.py"
  simulated_hardware_launch_file:
    package: "picknik_ur_base_config"
    path: "launch/sim/hardware_sim.launch.py"

  # Configuration details for cameras and scene planning.
  # [Required]
  camera_config_file:
    package: "picknik_ur_base_config"
    path: "config/cameras.yaml"

  # Parameters used to configure the robot description through XACRO.
  # A URDF and SRDF are both required.
  # [Required]
  robot_description:
    urdf:
      package: "picknik_ur_base_config"
      path: "description/picknik_ur5e.xacro"
    srdf:
      package: "picknik_ur_base_config"
      path: "config/moveit/picknik_ur5e.srdf"
    # Specify any additional parameters required for the URDF.
    # Many of these are specific to the UR descriptions packages, and can be customized as needed.
    # [Optional]
    urdf_params:
      - name: "%>> hardware.type"
      - prefix: ""
      - use_fake_hardware: "%>> hardware.simulated"
      - fake_sensor_commands: "false"
      - headless_mode: "true"
      - robot_ip: "%>> hardware.ip"
      - joint_limits_parameters_file:
          package: "picknik_ur_base_config"
          path: "config/moveit/joint_limits.yaml"
      # The following files are loaded based on the ur_description package layout.
      # To use parameters from a different package, place them in a config/ROBOT_NAME/ directory,
      # replace ROBOT_NAME with the value used for hardware.type in this file.
      - kinematics_parameters_file:
      # Load default_kinematics.yaml from ur_description/config/ur5e
          package: "ur_description"
          path: "config"
      - physical_parameters_file:
      # Load physical_parameters.yaml from ur_description/config/ur5e
          package: "ur_description"
          path: "config"
      - visual_parameters_file:
      # Load visual_parameters.yaml from ur_description/config/ur5e
          package: "ur_description"
          path: "config"

# Sets ROS global params for launch.
# [Required]
ros_global_params:
  # Whether or not to use simulated time.
  # [Required]
  use_sim_time: False

# Configure optional features in MoveIt Studio.
# [Required]
optional_feature_params:
  # Whether or not to use the Formant bridge for over-the-internet comms.
  # [Required]
  use_formant_bridge: False

# Configuration files for MoveIt.
# For more information, refer to https://moveit.picknik.ai/humble/doc/examples/examples.html#configuration
# [Required]
moveit_params:
  joint_group_name: "manipulator"

  ompl_planning:
    package: "picknik_ur_base_config"
    path: "config/moveit/ompl_planning.yaml"
  kinematics:
    package: "picknik_ur_base_config"
    path: "config/moveit/pick_ik_kinematics.yaml"
  servo:
    package: "picknik_ur_base_config"
    path: "config/moveit/ur5e_servo.yaml"
  sensors_3d:
    package: "picknik_ur_base_config"
    path: "config/moveit/sensors_3d.yaml"
  servo_kinematics:
    package: "picknik_ur_base_config"
    path: "config/moveit/pick_ik_kinematics_servo.yaml"
  joint_limits:
    package: "picknik_ur_base_config"
    path: "config/moveit/joint_limits.yaml"
  pilz_cartesian_limits:
    package: "picknik_ur_base_config"
    path: "config/moveit/pilz_cartesian_limits.yaml"

  publish:
    planning_scene: True
    geometry_updates: True
    state_updates: True
    transforms_updates: True

  trajectory_execution:
    manage_controllers: True
    allowed_execution_duration_scaling: 2.0
    allowed_goal_duration_margin: 5.0
    allowed_start_tolerance: 0.01

# Additional configurable parameters for the MoveIt Studio user interface.
# [Required]
ui_params:
  # By default, MoveIt Studio uses a frame called "manual_grasp_link" for tool grasp pose rendering
  # and planning.
  # [Required]
  servo_endpoint_frame_id: "manual_grasp_link"

# Configuration for launching ros2_control processes.
# [Required, if using ros2_control]
ros2_control:
  config:
    package: "picknik_ur_base_config"
    path: "config/control/picknik_ur5e.ros2_control.yaml"
  # MoveIt Studio will load and activate these controllers at start up to ensure they are available.
  # If not specified, it is up to the user to ensure the appropriate controllers are active and available
  # for running the application.
  # [Optional, default=[]]
  controllers_active_at_startup:
    - "force_torque_sensor_broadcaster"
    - "robotiq_gripper_controller"
    - "joint_state_broadcaster"
    - "streaming_controller"
    - "io_and_status_controller"
    - "robotiq_activation_controller"
  # Load but do not start these controllers so they can be activated later if needed.
  # [Optional, default=[]]
  controllers_inactive_at_startup:
    - "joint_trajectory_controller"
  # Any controllers here will not be spawned by MoveIt Studio.
  # [Optional, default=[]]
  controllers_not_managed: []
  # Optionally configure remapping rules to let multiple controllers receive commands on the same topic.
  # [Optional, default=[]]
  controller_shared_topics: []

# Configuration for loading behaviors and objectives. 
# [Required]
objectives:
  # List of plugins for loading custom behaviors.
  # [Required]
  behavior_loader_plugins:
    # This plugin will load the core MoveIt Studio behaviors.
    # Add additional plugin loaders as needed.
    core:
      - "moveit_studio::behaviors::CoreBehaviorsLoader"
  # Specify source folder for objectives
  # [Required]
  objective_library_paths:
    core:
      package_name: "picknik_ur_base_config"
      relative_path: "objectives"
  # Specify the location of the saved waypoints file.
  # [Required]
  waypoints_file:
    package_name: "picknik_ur_base_config"
    relative_path: "waypoints/ur5e_waypoints.yaml"
