# Joints limits
#
# Sources:
#
#  - Universal Robots e-Series, User Manual, UR5e, Version 5.8
#    https://s3-eu-west-1.amazonaws.com/ur-support-site/69091/99404_UR5e_User_Manual_en_Global.pdf
#  - Support > Articles > UR articles > Max. joint torques
#    https://www.universal-robots.com/articles/ur-articles/max-joint-torques
#    retrieved: 2020-06-16, last modified: 2020-06-09
#
# NOTE: Acceleration limits are not publicly available so we have picked a reasonable upper limit
joint_limits:
  shoulder_pan_joint:
    has_acceleration_limits: true
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_acceleration: !degrees 30.0
    max_effort: 150.0
    max_position: !degrees  180.0
    max_velocity: !degrees  30.0
    min_position: !degrees -180.0
  shoulder_lift_joint:
    has_acceleration_limits: true
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_acceleration: !degrees 30.0
    max_effort: 150.0
    max_position: !degrees  90.0
    max_velocity: !degrees  30.0
    min_position: !degrees -270.0
  elbow_joint:
    has_acceleration_limits: true
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_acceleration: !degrees 30.0
    max_effort: 150.0
    # we artificially limit this joint to half its actual joint position limit
    # to avoid (MoveIt/OMPL) planning problems, as due to the physical
    # construction of the robot, it's impossible to rotate the 'elbow_joint'
    # over more than approx +- 1 pi (the shoulder lift joint gets in the way).
    #
    # This leads to planning problems as the search space will be divided into
    # two sections, with no connections from one to the other.
    #
    # Refer to https://github.com/ros-industrial/universal_robot/issues/265 for
    # more information.
    max_position: !degrees  180.0
    max_velocity: !degrees  30.0
    min_position: !degrees -180.0
  wrist_1_joint:
    has_acceleration_limits: true
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_acceleration: !degrees 30.0
    max_effort: 28.0
    max_position: !degrees  180.0
    max_velocity: !degrees  60.0
    min_position: !degrees -180.0
  wrist_2_joint:
    has_acceleration_limits: true
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_acceleration: !degrees 30.0
    max_effort: 28.0
    max_position: !degrees  180.0
    max_velocity: !degrees  60.0
    min_position: !degrees -180.0
  wrist_3_joint:
    has_acceleration_limits: true
    has_effort_limits: true
    has_position_limits: true
    has_velocity_limits: true
    max_acceleration: !degrees 30.0
    max_effort: 28.0
    max_position: !degrees  180.0
    max_velocity: !degrees  60.0
    min_position: !degrees -180.0
  robotiq_85_left_knuckle_joint:
    has_velocity_limits: true
    max_velocity: 0.5
    has_acceleration_limits: true
    max_acceleration: 1.0
