manipulator:
  kinematics_solver: pick_ik/PickIkPlugin
  kinematics_solver_timeout: 0.01
  kinematics_solver_attempts: 1
  mode: global

  # Cost functions, weights, and thresholds
  rotation_scale: 0.5
  position_threshold: 0.001
  orientation_threshold: 0.001
  approximate_solution_position_threshold: 0.01
  approximate_solution_orientation_threshold: 0.01
  approximate_solution_joint_threshold: 0.1
  cost_threshold: 0.001
  minimal_displacement_weight: 0.001
  avoid_joint_limits_weight: 0.0

  # Gradient descent options
  gd_max_iters: 100
  gd_step_size: 0.0001
