#
#  This contains information for a unique instance of a robot.
#

# Name of the package to specialize
based_on_package: "picknik_ur_gazebo_config"

hardware:
  # The following launch file is started when hardware.simulated is True
  simulated_hardware_launch_file:
    package: "picknik_ur_gazebo_scan_and_plan_config"
    path: "launch/sim/hardware_sim.launch.py"

objectives:
  # Override with a new set of waypoints based on the Gazebo world.
  waypoints_file:
    package_name: "picknik_ur_gazebo_scan_and_plan_config"
    relative_path: "waypoints/waypoints.yaml"
  # Add new simulation Objectives in addition to the one in the base config package.
  objective_library_paths:
    sim:
      package_name: "picknik_ur_gazebo_scan_and_plan_config"
      relative_path: "objectives"
