#
#  This contains information for a unique instance of a robot.
#

# Name of the package to specialize
based_on_package: "picknik_ur_site_config"

# Optional parameters that can be read in your launch files for specific functionality
# optional_feature_params:
#   gazebo_world_name: "space_station_blocks_world.sdf"
#   gazebo_gui: False
#   gazebo_verbose: True

# Enable simulation time so nodes are synced with the Gazebo block.
ros_global_params:
  use_sim_time: True

hardware:
  # This is the only option for this site_config
  simulated: True

  # Gazebo starts its own controller manager through the ros2_control plugin, so set this to False
  launch_control_node: False

  # If the MoveIt Pro Agent should launch the robot state publisher
  # This should be false if you are launching the robot state publisher as part of drivers.
  launch_robot_state_publisher: True

  # The following launch file is started when hardware.simulated is True
  simulated_hardware_launch_file:
    package: "picknik_ur_gazebo_config"
    path: "launch/sim/hardware_sim.launch.py"

  robot_description:
    urdf:
      package: "picknik_ur_gazebo_config"
      path: "description/picknik_ur_gazebo.xacro"
    srdf:
      package: "picknik_ur_gazebo_config"
      path: "config/moveit/picknik_ur_gazebo.srdf.xacro"
    urdf_params:
      - name: "ur5e"
      - gripper_name: "robotiq_85"
      - use_pinch_links: "false"
      - simulation: "gazebo"
      - kinematics_parameters_file:
          # Load default_kinematics.yaml from ur_description/config/<ur_type>
          package: "ur_description"
          path: "config/ur5e/default_kinematics.yaml"
      - physical_parameters_file:
          # Load physical_parameters.yaml from ur_description/config/<ur_type>
          package: "ur_description"
          path: "config/ur5e/physical_parameters.yaml"
      - visual_parameters_file:
          # Load visual_parameters.yaml from ur_description/config/<ur_type>
          package: "ur_description"
          path: "config/ur5e/visual_parameters.yaml"

# Override MoveIt parameters
moveit_params:
  sensors_3d:
    package: "picknik_ur_gazebo_config"
    path: "config/moveit/sensors_3d.yaml"
  servo:
    package: "picknik_ur_gazebo_config"
    path: "config/moveit/ur_servo.yaml"

# This configures what controllers gets run at startup
ros2_control:
  controllers_active_at_startup:
    - "joint_state_broadcaster"
    - "streaming_controller"
    - "robotiq_gripper_controller"
  controllers_inactive_at_startup:
    - "joint_trajectory_controller"
    - "servo_controller"

objectives:
  # Override with a new set of waypoints based on the Gazebo world.
  waypoints_file:
    package_name: "picknik_ur_gazebo_config"
    relative_path: "waypoints/waypoints.yaml"
  # Add new simulation Objectives in addition to the one in the base config package.
  objective_library_paths:
    sim:
      package_name: "picknik_ur_gazebo_config"
      relative_path: "objectives"
