SetupMTCApproachGrasp:
  world_frame_name: "world"
  arm_group_name: "manipulator"
  end_effector_group_name: "gripper"
  end_effector_name: "moveit_ee"
  hand_frame_name: "grasp_link"

  approach_distance: 0.05

  enforce_visibility_constraint: true
  camera_optical_frame_id: wrist_mounted_camera_color_optical_frame
  camera_field_of_view_angle: 1.0472
  sensor_z_offset: 0.0
  target_diameter: 0

SetupMTCGenerateVacuumGrasps:
  end_effector_group_name: "gripper"
  end_effector_name: "moveit_ee"
  hand_frame_name: "grasp_link"
  end_effector_closed_pose_name: "close"
  ui_grasp_link: "grasp_link"

  # Grasp candidate configs
  grasp_candidate_config:
    # If true, generate grasps at the centroid of each surface
    generate_centroid_grasps: true

    # Padding on planar faces to avoid sampling on edges.
    padding_dimension: 0.01

    # Number of samples to generate
    samples_per_plane: 1
    num_orientation_samples: 4

  # Grasp data configs
  grasp_data:
    # The transform from the arm IK link to the grasp point to align it with the following convention.
    #
    # z-axis pointing toward object to grasp
    # x-axis perpendicular to movement of grippers
    # y-axis parallel to movement of grippers
    eef_mount_to_tcp_transform:
      x: 0.0
      y: 0.0
      z: 0.0
      roll: 0.0
      pitch: 0.0
      yaw: 1.57

SetupMTCGenerateCuboidGrasps:
  end_effector_group_name: "gripper"
  end_effector_name: "moveit_ee"
  hand_frame_name: "grasp_link"
  end_effector_closed_pose_name: "close"
  ui_grasp_link: "grasp_link"

  grasp_candidate_config:
    generate_x_axis_grasps: true
    generate_y_axis_grasps: true
    generate_z_axis_grasps: true
    samples_per_quadrant: 3

  grasp_data:
    eef_mount_to_tcp_transform:
      pitch: 0
      roll: 0
      x: 0
      y: 0
      yaw: 1.57
      z: 0
    grasp_max_depth: 0.035
    grasp_min_depth: 0.01
    max_grasp_width: 0.1

SetupMTCRetractFromGrasp:
  world_frame_name: "world"
  arm_group_name: "manipulator"
  end_effector_group_name: "gripper"
  hand_frame_name: "grasp_link"
  end_effector_closed_pose_name: "close"

  approach_distance: 0.15
  lift_distance: 0.1
