SetupMTCOpenDoorAffordance:
  arm_group_name: "manipulator"
  end_effector_group_name: "gripper"
  end_effector_name: "moveit_ee"
  ik_frame_name: "manual_grasp_link"
  end_effector_closed_pose_name: "close"
  end_effector_open_pose_name: "open"

  # List of controllers to use during the stages that interact with the door.
  # For this objective, we want to enable admittance control.
  door_opening_controllers: "/joint_trajectory_controller_chained_open_door /admittance_controller_open_door /robotiq_gripper_controller"

  approach_distance: 0.05
  translation_distance: 0.0
  rotation_distance: 60.0
  use_circular_arc: true
