SetupMTCGraspThenMoveAlongArcPull:
  arm_group_name: "manipulator"
  end_effector_group_name: "gripper"
  end_effector_name: "moveit_ee"
  ik_frame_name: "grasp_link"
  end_effector_closed_pose_name: "close"
  end_effector_open_pose_name: "open"

  # List of controllers to use during the stages that interact with the door.
  move_along_arc_controllers: "/joint_trajectory_controller_chained_open_door /admittance_controller_open_door /robotiq_gripper_controller"

  approach_distance: 0.05   # meters
  translation_distance: 0.0   # meters (0 means only move along arc here, no linear component)
  rotation_distance: 50.0  # Degrees
  use_circular_arc: true
