AllowGripperCollisionWithOctomap:
  group_name: "gripper"
  object_name: "<octomap>"
  allow_collision: true

ForbidGripperCollisionWithOctomap:
  group_name: "gripper"
  object_name: "<octomap>"
  allow_collision: false
