sensors:
  - scene_scan_camera
scene_scan_camera:
  # The name of the Octomap updater plugin that we are using.
  sensor_plugin: "occupancy_map_monitor/PointCloudOctomapUpdater"
  # Specifies the topic to listen on for a point cloud.
  # Set to an empty topic to disable.
  point_cloud_topic: "/scene_camera/depth/color/points/snapshot"
  # Points further than this will not be used (in meters).
  max_range: 1.5
  # Choose one of every 'point_subsample' points (select all if set to 1).
  point_subsample: 1
  # Should always be >= 1.0. Scale up collision shapes in the scene before excluding them from the octomap.
  padding_scale: 1.0
  # Absolute padding around scaled collision shapes when excluding them from the octomap (in meters).
  padding_offset: 0.05
  # The octomap representation will be updated at rate less than or equal to this value.
  max_update_rate: 0.1
  # The topic on which the filtered cloud will be published (mainly for debugging).
  # The filtering cloud is the resultant cloud after self-filtering has been performed.
  # Set to an empty topic to disable.
  filtered_cloud_topic: ""

# Specifies the resolution at which the octomap is maintained (in meters).
octomap_resolution: 0.03
# Specifies the coordinate frame in which the Octomap representation will be stored.
# Note! When an OccupancyMonitor instance is initialized by the PlanningSceneMonitor,
# this frame parameter will not be used. Instead, the frame defaults to the planning frame.
octomap_frame: "base_link"
