controller_manager:
  ros__parameters:
    update_rate: 600  # Hz
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    joint_trajectory_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    robotiq_gripper_controller:
      type: position_controllers/GripperActionController
    servo_controller:
      type: joint_trajectory_controller/JointTrajectoryController
    force_torque_sensor_broadcaster:
      type: force_torque_sensor_broadcaster/ForceTorqueSensorBroadcaster
    joint_trajectory_admittance_controller:
      type: joint_trajectory_admittance_controller/JointTrajectoryAdmittanceController
    velocity_force_controller:
      type: velocity_force_controller/VelocityForceController


joint_state_broadcaster:
  ros__parameters:
    use_local_topics: false
    joints:
      - linear_rail_joint
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
      - robotiq_85_left_knuckle_joint
    interfaces:
      - position
      - velocity
      - effort

joint_trajectory_controller:
  ros__parameters:
    joints:
      - linear_rail_joint
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    command_joints:
      - linear_rail_joint
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.0
      goal_time: 0.0
      linear_rail_joint:
        goal: 0.05
      shoulder_pan_joint:
        goal: 0.05
      shoulder_lift_joint:
        goal: 0.05
      elbow_joint:
        goal: 0.05
      wrist_1_joint:
        goal: 0.05
      wrist_2_joint:
        goal: 0.05
      wrist_3_joint:
        goal: 0.05
    acceleration_limits:
      linear_rail_joint: 10.0
      shoulder_pan_joint: 10.0
      shoulder_lift_joint: 10.0
      elbow_joint: 10.0
      wrist_1_joint: 10.0
      wrist_2_joint: 10.0
      wrist_3_joint: 10.0

robotiq_gripper_controller:
  ros__parameters:
    default: true
    joint: robotiq_85_left_knuckle_joint
    allow_stalling: true
servo_controller:
  ros__parameters:
    joints:
      - linear_rail_joint
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint

    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity
    command_joints:
      - linear_rail_joint
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    state_publish_rate: 100.0
    action_monitor_rate: 20.0
    allow_partial_joints_goal: false
    constraints:
      stopped_velocity_tolerance: 0.0
      goal_time: 0.0
      linear_rail_joint:
        goal: 0.05
      shoulder_pan_joint:
        goal: 0.05
      shoulder_lift_joint:
        goal: 0.05
      elbow_joint:
        goal: 0.05
      wrist_1_joint:
        goal: 0.05
      wrist_2_joint:
        goal: 0.05
      wrist_3_joint:
        goal: 0.05
    acceleration_limits:
      linear_rail_joint: 10.0
      shoulder_pan_joint: 10.0
      shoulder_lift_joint: 10.0
      elbow_joint: 10.0
      wrist_1_joint: 10.0
      wrist_2_joint: 10.0
      wrist_3_joint: 10.0

force_torque_sensor_broadcaster:
  ros__parameters:
    sensor_name: robotiq_ft_sensor
    state_interface_names:
      - force.x
      - force.y
      - force.z
      - torque.x
      - torque.y
      - torque.z
    frame_id: robotiq_ft_sensor


joint_trajectory_admittance_controller:
  ros__parameters:
    joints:
      - linear_rail_joint
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    base_frame: base_link
    sensor_frame: tool0
    ee_frame: grasp_link
    ft_sensor_name: robotiq_ft_sensor
    # Joint accelerations chosen to match MoveIt configs.
    stop_accelerations:
      - 30.0
      - 30.0
      - 30.0
      - 30.0
      - 30.0
      - 30.0
      - 30.0

velocity_force_controller:
  ros__parameters:
    joints:
      - linear_rail_joint
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
    base_frame: base_link
    sensor_frame: tool0
    ee_frame: grasp_link
    ft_sensor_name: robotiq_ft_sensor
    ft_force_deadband: 2.0
    ft_torque_deadband: 1.0
    max_joint_velocity:
      - 0.524
      - 0.524
      - 0.524
      - 0.524
      - 1.047
      - 1.047
      - 1.047
    max_joint_acceleration:
      - 0.524
      - 0.524
      - 0.524
      - 0.524
      - 0.524
      - 0.524
      - 0.524
    max_cartesian_velocity:
      - 0.25
      - 0.25
      - 0.25
      - 1.5707
      - 1.5707
      - 1.5707
    max_cartesian_acceleration:
      - 2.0
      - 2.0
      - 2.0
      - 4.0
      - 4.0
      - 4.0
