<?xml version="1.0" encoding="utf-8"?>
<robot xmlns:xacro="http://ros.org/wiki/xacro">
  <!-- radius of wrist_2_link/forearm_link is ~0.045m. Actual offset of this is (radius - attached_link's radius) -->
  <xacro:macro name="pinch_link" params="prefix:='' connected_to:='forearm_link' length:=0.28 radius:=0.0675">
    <xacro:property name="prefix_" value='${prefix + "_" if prefix else ""}' />
    <link name="pinch_link">
      <visual>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
          <cylinder length="${length}" radius="${radius}"/>
        </geometry>
        <material name="silver">
          <color rgba="0.75 0.65 0.65 0"/>
        </material>
      </visual>
      <collision>
        <origin xyz="0 0 0" rpy="0 0 0"/>
        <geometry>
            <cylinder length="${length}" radius="${radius}"/>
        </geometry>
      </collision> 
    </link>

    <joint name="${prefix_}pinch_joint" type="fixed">
      <parent link="${connected_to}"/>
      <child link="pinch_link"/>
      <origin xyz="${-0.08 - length/2} 0 0.0049" rpy="0 ${pi/2} 0" />
    </joint>
  </xacro:macro>
</robot>
