name: CI
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
  # Run every 6 hours Mon-Fri
  schedule:
    - cron: "0 */6 * * 1-5"

jobs:
  integration-test-in-studio-container:
    uses: PickNikRobotics/reusable_ci/.github/workflows/workspace_integration_test.yaml@workspace_integration
    secrets: inherit
