name: CI
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
  # Run every 6 hours Mon-Fri
  schedule:
    - cron: "0 */6 * * 1-5"

jobs:
  setup:
    runs-on: ubuntu-latest
    outputs:
      image_tag: ${{ steps.dotenv.outputs.studio_docker_tag }}
    steps:
      - uses: actions/checkout@v4
      - id: dotenv
        uses: falti/dotenv-action@v1.0.4

  integration-test-in-studio-container:
    needs: setup
    uses: PickNikRobotics/reusable_ci/.github/workflows/workspace_integration_test.yaml@workspace_integration
    with:
      image_tag: "${{ needs.setup.outputs.image_tag }}"
    secrets: inherit