name: CI
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
jobs:
  integration-test-in-studio-container:
    runs-on: ubuntu-latest
    env:
      USER_WS: /github/workspace
    # TODO: docker tag
    # TODO: example for custom base images
    container: picknikciuser/moveit-studio:main
    steps:
      - uses: actions/checkout@v4
      - name: Run colcon build and test
        run: |
          . /opt/ros/humble/setup.sh
          . /opt/underlay_ws/install/setup.sh
          . /opt/overlay_ws/install/setup.sh
          colcon build
          colcon test
          colcon test-result
