name: CI
on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:
    inputs:
      image_tag:
        description: 'The tag of the image to use for the container'
        required: false
        default: ''
  # Run every 6 hours Mon-Fri
  schedule:
    - cron: "0 */6 * * 1-5"

jobs:
  integration-test-in-studio-container:
    uses: PickNikRobotics/moveit_pro_ci/.github/workflows/workspace_integration_test.yaml@virtual-buffer
    with:
      image_tag: ${{ github.event.inputs.image_tag || null }}
      colcon_test_args: "--executor sequential"
    secrets: inherit

  ensure-no-ssh-in-gitmodules:
    name: Ensure no SSH URLs in .gitmodules
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3
      - name: Check .gitmodules file for Git-over-SSH URLs
        run: "! grep 'git@' .gitmodules"
